apiVersion: v1
kind: Service
metadata:
  labels:
    service: ksqldb-server
  name: ksqldb-server
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    service: ksqldb-server
status:
  loadBalancer: {}
